config/routes.rb
SquashLeague::Application.routes.draw do
  root  'home#index'
  resources :sessions, only: [:new, :create, :destroy]
  
  get "users/login"
  get "players/get_player"
  get "users/get_user"
  
  
  get "league/home"
  get "league/players"
  get "league/schedule"
  get "league/player_history"
  get "league/history"
  
  get "users/dashboard_main"
  
	get "admin/admin_dashboard"
	get "admin/match_controls"
	get "admin/new_season"
	post "admin/create_season"
	get "admin/manage_seasons"
	get "admin/new_player"
	post "admin/manage_player"
	get "admin/manage_players"
	get "admin/new_user"
	post "admin/manage_user"
	get "admin/manage_users"
	post "admin/create_user"
	post "admin/create_player"
	post "admin/reset_user_password"
	
	match '/news', to: 'home#news', via: 'get'

  get "match/show"
  patch "match/edit"
	
	match '/signin', to: 'sessions#new', via: 'get'
	match '/signout', to: 'sessions#destroy', via: 'delete'
	
  get "users/settings"
  post "users/update_details"
  post "users/update_password"
  
  post "post/create"
  get "post/show"
  get "post/new"
  patch "post/update"
  delete "post/delete"

  

end

app/views/admin/admin_dashboard.html.erb
<ul>
	<li><%= link_to "Create Player", admin_new_player_path %></li>
	<li><%= link_to "Manage Players", admin_manage_players_path %></li>
	<li><%= link_to "Create Season", admin_new_season_path %></li>
	<li><%= link_to "Manage Seasons (Can only mark current season as complete)", admin_manage_seasons_path %></li>
	<li><%= link_to "Create User", admin_new_user_path %></li>
	<li><%= link_to "Manage Users", admin_manage_users_path %></li>
	<li><%= link_to "Manage Matches", admin_match_controls_path %></li>
	<li>??</li>
	<li>??</li>
	<li>??</li>
</ul>

app/views/admin/manage_players.html.erb
<script src="/assets/admin.js" type="text/javascript"></script>





<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Manage Players</h3>
    <br/>
		<i>This is used to manage players.
		<br/>
		Page loads list of players. User selects the player to modify. 
		<br/>
		Javascript populates user information into the form. User makes the modification and POSTS update.
		</i>
  </div>
  <div class="panel-body">
    <div class="row">
			<div class="col-md-2">
				<ul class="nav nav-pills nav-stacked">
				<% @players.each do |player| %>
					<li>
						<a href="#" onclick="retrieve_player('<%= player.id %>')"><%= player.first_name + " " + player.last_name %></a>
					</li>
				<% end %>
				</ul>
			</div>
			<div class="col-md-10">
				<%= form_for(:player, :url => url_for(:action => "manage_player"), :html => {:class => "form-horizontal"}) do |f| %>

					<%= f.hidden_field :id %>

					<div class="form-group">
						<label class="control-label col-md-1">First Name</label>
						<div class="col-md-6">
							<%= f.text_field(:first_name, :class=>"form-control") %>
						</div>
					</div>
	
					<div class="form-group">
						<label class="control-label col-md-1">Last Name</label>
						<div class="col-md-6">
							<%= f.text_field(:last_name, :class=>"form-control") %>
						</div>
					</div>
	
					<div class="form-group">
						<div class="col-md-offset-1 col-md-1">
							<%= f.submit "Update", class: "btn btn-large btn-default" %>	
						</div>
					</div>
					
				<% end %>
			</div>
		</div>
  </div>
</div>

app/views/admin/manage_seasons.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Manage Seasons</h3>
  </div>
  <div class="panel-body">
    <table class="table">
    	<thead>
    		<tr>
    			<th>Season Name</th>
    			<th>Season Winner</th>
    			<th>Season Start</th>
    			<th>Season End</th>
    			<th>Season Status</th>
    			<th>MPPP</th>
    			<th>Division</th>
    			<th>Edit Matches</th>
    		</tr>
    	</thead>
    	<tbody>
    		<% @seasons.each do |season| %>
    		<tr>
    			<td><%= season.season_name %></td>
    			<td><%= season.winner_name %></td>
    			<td><%= season.season_start %></td>
    			<td><%= season.season_end %></td>
    			<td><%= season.season_status %></td>
    			<td><%= season.matches_per_player_pair %></td>
    			<td><%= season.division_level %></td>
    			<td><%= link_to "edit matches", admin_match_controls_path(:sid => season.id)%></td>
    		</tr>
    		<% end %>
    	</tbody>
    </table>
  </div>
</div>

app/views/admin/manage_users.html.erb
<script src="/assets/admin.js" type="text/javascript"></script>




<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Manage Users</h3>
    <i>
			This is used to manage players.
			<br/>
			Page loads list of players. Admin selects the User to modify. User to Player link is created here.
			<br/>
			Javascript populates user information into the form. User makes the modification and POSTS update.
    </i>
  </div>
  <div class="panel-body">
		<div class="row">
			<div class="col-md-2">
				<ul class="nav nav-pills nav-stacked">
				<% @users.each do |user| %>
					<li>
						<a href="#" onclick="retrieve_user('<%= user.id %>')"><%= user.name %></a>
					</li>
				<% end %>
				</ul>
			</div>
			<div class="col-md-10">
				<%= form_for(:user, :url => url_for(:action => "manage_user"), :html => {:class => "form-horizontal"}) do |f| %>

					<%= f.hidden_field :id %>

					<div class="form-group">
						<label class="control-label col-md-1">Name</label>
						<div class="col-md-6">
							<%= f.text_field(:name, :class=> "form-control") %>
						</div>
					</div>
			
					<div class="form-group">
						<label class="control-label col-md-1">Player</label>
						<div class="col-md-6">
							<select name="user_player" id="user_player" class="form-control">
								<option value="">----</option>
								<% @players.each do |player| %>
									<option user_id="<%= player.user_id %>" value="<%= player.id %>"><%= player.full_name_abs %></option>
								<% end %>
							</select>
						</div>
					</div>
			
		
					<div class="form-group">
						<div class="col-md-offset-1 col-md-1">
							<%= f.submit "Update", class: "btn btn-large btn-default" %>	
						</div>
					</div>
				  
				<% end %>
				<%= form_for(:user, :url => url_for(:action => "reset_user_password"), :html => {:class => "form-horizontal"}) do |f| %>
				<%= f.hidden_field :id %>
				<div class="form-group">
						<div class="col-md-offset-1 col-md-1">
							<%= f.submit "Reset Password", class: "btn btn-large btn-default" %>	
						</div>
					</div>
				<%end%>
			</div>
		</div>
  </div>
</div>

app/views/admin/match_controls.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Match Controls for <b><%= @season.season_name %></b></h3>
    <i>List of matches in current season, user can click which one to update. next view should open matches and games that can be edited.</i>
  </div>
  <div class="panel-body">
    <table class="table">
    	<thead>
    		<tr>
    			<th>Match ID</th>
    			<th>Player 1</th>
    			<th>Player 2</th>
    			<th>Winner</th>
    			<th>Status</th>
    			<th>Round</th>
    		</tr>
    	</thead>
    	<tbody>
    		<% @matches.each do |match| %>
    			<tr>
    				<td><%= link_to match.id, match_show_path(:id => match.id) %></td>
    				<td><%= match.player_full_name(match.player1_id) %></td>
    				<td><%= match.player_full_name(match.player2_id) %></td>
    				<td><%= match.player_full_name(match.winner_id) %></td>
    				<td><%= match.status %></td>
    				<td><%= match.round_name %></td>
    			</tr>
    		<% end %>
    	</tbody>
    </table>
  </div>
</div>

app/views/admin/new_player.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Create New Player</h3>
    <i>This is used to create a new player. Rule: No duplicate players. (ie, fname, lname have to be unique)</i>
  </div>
  <div class="panel-body">
		<div class="row">
			<div class="">
				<%= form_for(:player, :url => url_for(:action => "create_player"), :html => {:class => "form-horizontal"}) do |f| %>

					<div class="form-group">
						<label class="control-label col-md-2">First Name</label>
						<div class="col-md-6">
							<%= f.text_field(:first_name , :class => "form-control") %>
						</div>
					</div>
		
					<div class="form-group">
						<label class="control-label col-md-2">Last Name</label>
						<div class="col-md-6">
							<%= f.text_field(:last_name , :class => "form-control") %>
						</div>
					</div>
		
					<div class="form-group">
						<div class="col-md-offset-2 col-md-1">
							<%= f.submit "Create", class: "btn btn-large btn-default" %>	
						</div>
					</div>
				  
				  
				<% end %>
			</div>
		</div>
  </div>
</div>

app/views/admin/new_season.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
    <i>
			Can create new season. 
			Choose players that will be competing in the new season. 
			Number of matches per player pair. 
			Start and End dates for Players. 
			Button to Generate new Season and Season Schedule.
    </i>
  </div>
  <div class="panel-body">
		<div class="row">
				<%= form_for(:season, :url => url_for(:action => "create_season"), :html => {:class => "form-horizontal"}) do |f| %>
				<div class="col-md-9">
					<div class="form-group">
						<label class="control-label col-md-3">Season Name</label>
						<div class="col-md-6">
							<%= f.text_field(:season_name, :class=>"form-control")%>
						</div>
					</div>
		
					<div class="form-group">
						<label class="control-label col-md-3">Season Start</label>
						<div class="col-md-6">
							 <%= date_field(:season, :season_start, :class=>"form-control") %>
						</div>
					</div>
		
				<div class="form-group">
						<label class="control-label col-md-3">Division</label>
						<div class="col-md-6">
							<select name="division_id" class="form-control">
								<option value="">----</option>
								<% @divisions.each do |division| %>
									<option value="<%= division.id %>"><%= division.division_level %></option>
								<% end %>
							</select>
						</div>
					</div>
		
					<div class="form-group">
						<label class="control-label col-md-3">Matches Per Player-Pair</label>
						<div class="col-md-6">
							<%= f.number_field(:matches_per_player_pair, :class=>"form-control") %>
						</div>
					</div>
		
					<div class="form-group">
						<label class="control-label col-md-3">Grace Period in Weeks</label>
						<div class="col-md-6">
							<input type="number" class="form-control" name="grace_period" value="" />
						</div>
					</div>
					
					<div class="form-group">
						<div class="col-md-offset-3 col-md-1">
							<%= f.submit "Create Season", class: "btn btn-large btn-default" %>	
						</div>
					</div>
			</div>
			<div class="col-md-3 form-horizontal">
				<% @players.each do |player| %>
					<div class="checkbox">
						<label>
							<input name="player_id[<%= player.id %>]" class="form-control" type="checkbox" value="<%= player.id %>" />
							<%= player.full_name_abs %>
						</label>
					</div>
				<% end %>
			</div>
			<% end %>
		</div>
  </div>
</div>

app/views/admin/new_user.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New User</h3>
    <i>Allows user to create new user. once the new user is created, an email is sent to the user? or the admin has to send the email and password to the user?
			<br>
			password is auto-generated, and emailed to the user
		</i>
  </div>
  <div class="panel-body">
		<div class="row">
			<div class="">
			<%= form_for @user, :html => { :class => "form-horizontal" }, :url => url_for(:controller => "admin", :action => "create_user") do |f| %>
					<%= render "shared/error_messages" %>
					<div class="form-group">
						<label class="control-label col-md-1">Name</label>
						<div class="col-md-6">
							<%= f.text_field(:name, :class=> "form-control") %>
						</div>
					</div>

					<div class="form-group">
						<label class="control-label col-md-1">Email</label>
						<div class="col-md-6">
							<%= f.text_field(:email, :class=> "form-control") %>
						</div>
					</div>
		
					<div class="form-group">
						<div class="col-md-offset-1 col-md-1">
							<%= f.submit "Create New User", class: "btn btn-large btn-default" %>	
						</div>
					</div>
				  
				  
				<% end %>
			</div>
		</div>
  </div>
</div>