config/routes.rb
SquashLeague::Application.routes.draw do
  root  'home#index'
  resources :sessions, only: [:new, :create, :destroy]
  
  get "users/login"
  get "players/get_player"
  get "users/get_user"
  
  
  get "league/home"
  get "league/players"
  get "league/schedule"
  get "league/player_history"
  get "league/history"
  
  get "users/dashboard_main"
  
	get "admin/admin_dashboard"
	get "admin/match_controls"
	get "admin/new_season"
	post "admin/create_season"
	get "admin/manage_seasons"
	get "admin/new_player"
	post "admin/manage_player"
	get "admin/manage_players"
	get "admin/new_user"
	post "admin/manage_user"
	get "admin/manage_users"
	post "admin/create_user"
	post "admin/create_player"
	post "admin/reset_user_password"
	
	match '/news', to: 'home#news', via: 'get'

  get "match/show"
  patch "match/edit"
	
	match '/signin', to: 'sessions#new', via: 'get'
	match '/signout', to: 'sessions#destroy', via: 'delete'
	
  get "users/settings"
  post "users/update_details"
  post "users/update_password"
  
  post "post/create"
  get "post/show"
  get "post/new"
  patch "post/update"
  delete "post/delete"

  

end

app/views/layouts/_footer.html.erb
<div id="footer">
      <div class="container">
        <p class="text-muted credit"> Built by Sai using Twitter Bootstrap</p>
      </div>
    </div>

app/views/layouts/_login_dropdown.html.erb
<% if signed_in? %>
  <li id="fat-menu" class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= @current_user.email %> <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
			<% if is_admin? %>
				<li><%= link_to "Admin Dashboard", admin_admin_dashboard_path %></li>
			<% end %>
			<li><%= link_to "User Dashboard", users_dashboard_main_path %></li>
      <li><%= link_to "Settings", users_settings_path %></li>
      <li class="divider"></li>
      <li>
        <%= link_to "Sign out", signout_path, method: "delete" %>
      </li>
    </ul>
  </li>
<% else %>
  <li><%= link_to "Sign in", signin_path %></li>
<% end %>

app/views/layouts/_navbar.html.erb
 <div class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
		  <%= link_to "Squash League", root_path, {:class => "navbar-brand #{@sl_active}"} %>
			<button class="navbar-toggle collapsed" data-target=".bs-navbar-collapse" data-toggle="collapse" type="button">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>          
		</div>
		<nav class="navbar-collapse bs-navbar-collapse collapse" role="navigation" style="height: 1px;">
			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">League Table <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><%= link_to "Standings", league_home_path %></li>
						<li><%= link_to "Fixtures & Results", league_schedule_path %></li>
						<li><a href="#">Players</a></li>
						<!--<li><%= link_to "Players", league_players_path %></li>
						<li class="divider"></li>
						<li class="dropdown-header">History</li>
						<li><%= link_to "Player History", league_player_history_path %></li>
						<li><%= link_to "League History", league_history_path %></li>-->
					</ul>
				</li>
				<!--<li><%= link_to "News", news_path %></li>-->
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<%= render "layouts/login_dropdown" %>
			</ul>
		</nav>	  
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Squash League</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navbar" %>

 <div style="margin-top:70px;" class="container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>">
				<% if value.class == String %>
					<%= value %>					
				<% else %>
					<% value.each do |val| %>
						<%= val %>
						<br />
					<% end %>
				<% end %>
				</div>
      <% end %>
			<%= yield %>
    </div>

</body>
<footer>
	<%= render "layouts/footer" %>
</footer>
</html>